name: Duster Linting

run-name: ${{ github.actor }} is checking linting.

on: [push]

jobs:
  duster:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "Duster Lint"
        uses: tighten/duster-action@v1
        with:
          args: lint
