name: Pest Feature Tests

run-name: ${{ github.actor }} is running PHPUnit tests.

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['8.2', '8.3']

    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install composer dependencies
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Setup Application
        run: cp .env.example .env && php artisan key:generate

      - name: Install node dependencies
        run: npm install && npm run build

      - name: Run tests
        run: ./vendor/bin/pest --group=Feature -p
